name: Ejecutar RSI desde main2.py

on:
  schedule:
    - cron: "30 13 * * *"   # 8:30 AM NY
    - cron: "35 13 * * *"   # 8:35 AM NY
    - cron: "0 0 * * *"     # 7:00 PM NY
    - cron: "5 0 * * *"     # 7:05 PM NY
  workflow_dispatch:

jobs:
  ejecutar-rsi:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install gspread oauth2client tradingview_ta

      - name: Ejecutar script principal
        run: python main2.py
